# Generated by Django 4.1.2 on 2022-10-07 02:38

from django.db import migrations

def populate_status(apps, schemaeditor):
    statuses = {
        "to do": "An issue that has not been started yet",
        "in progress": "An issue that is actively being worked on",
        "done": "An issue that has successfully been completed",
    }
    Status = apps.get_model("issues", "Status")
    for key, desc in statuses.items():
        status_obj = Status(name=key, description=desc)
        status_obj.save()

def populate_impact(apps, schemaeditor):
    impacts = {
        "critical": "The measure of high effect (positive or negative) of an issue",
        "significant": "The measure of medium effect (positive or negative) of an issue",
        "minor": "The measure of low effect (positive or negative) of an issue",
    }
    Impact = apps.get_model("issues", "Impact")
    for key, desc in impacts.items():
        impact_obj = Impact(name=key, description=desc)
        impact_obj.save()

def populate_urgency(apps, schemaeditor):
    urgencies = {
        "high": "The measure of shortest due date of an issue",
        "medium": "The measure of medium due date of an issue",
        "low": "The measure of longest due date of an issue",
    }
    Urgency = apps.get_model("issues", "Urgency")
    for key, desc in urgencies.items():
        urgency_obj = Urgency(name=key, description=desc)
        urgency_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_impact),
                migrations.RunPython(populate_urgency), 
                migrations.RunPython(populate_status)
    ]
