# Generated by Django 4.1.2 on 2022-10-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_auto_20221013_2312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.ForeignKey(
                default="TO DO",
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.status",
            ),
        ),
    ]
