# Generated by Django 4.1.2 on 2022-10-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_alter_issue_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
