# Generated by Django 4.1.2 on 2022-10-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_issuecreateviewcustomer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="issues.status"
            ),
        ),
    ]
