# Generated by Django 4.1.2 on 2022-10-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_alter_issue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.status",
            ),
        ),
    ]
