# Generated by Django 4.1.2 on 2022-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Customer", "Customer"),
                    ("Agent", "Agent"),
                    ("Manager", "Manager"),
                ],
                default="Customer",
                max_length=255,
                null=True,
            ),
        ),
    ]
